using CotizadorInterno.Web.Models;
using CotizadorInterno.Web.Models.Calculator;
using CotizadorInterno.Web.Models.CuentasCobro;
using CotizadorInterno.Web.Models.Copiers;
using CotizadorInterno.Web.Models.Dashboard;
using CotizadorInterno.Web.Models.Hardware;
using CotizadorInterno.Web.Models.Licenciamiento;
using CotizadorInterno.Web.Models.Metricas;
using CotizadorInterno.Web.Models.Nomina;
using CotizadorInterno.Web.Models.Permissions;
using CotizadorInterno.Web.Models.PortalProveedores;
using CotizadorInterno.Web.Models.Puntajes;
using CotizadorInterno.Web.Models.RH;
using CotizadorInterno.Web.Models.Renovaciones;
using CotizadorInterno.Web.Models.SoporteCloud;

namespace CotizadorInterno.Web.Services;

public interface IDataverseService
{
    Task<IReadOnlyList<ProductLookupItem>> SearchProductsAsync(string query, int top = 12, CancellationToken ct = default);
    Task<ProductLookupItem> EnsureCalculatorProductAsync(ProductCreateInput input, CancellationToken ct = default);
    Task<IReadOnlyList<ClientLookupItem>> SearchClientsAsync(string query, int top = 12, CancellationToken ct = default);
    Task<IReadOnlyList<SystemUserLookupItem>> SearchSystemUsersAsync(string query, int top = 12, CancellationToken ct = default);
    Task<IReadOnlyList<RenewalDateLookupItem>> SearchRenewalDatesByClientAsync(string clientId, int top = 250, CancellationToken ct = default);
    Task<CurrentUserInfo?> GetCurrentUserAsync(CancellationToken ct = default);
    Task<RenewalBoardDto> GetRenewalBoardAsync(RenewalPeriodFilter filter, CancellationToken ct = default);
    Task<int> UpdateRenewalRecordsAsync(IReadOnlyList<RenewalRecordUpdateItem> items, CancellationToken ct = default);
    Task<RenewalScenarioCreateResultDto> CreateRenewalScenarioAsync(IReadOnlyList<RenewalRecordUpdateItem> items, CancellationToken ct = default);
    Task<ScoreBoardDto> GetScoreBoardAsync(ScorePeriodFilter filter, CancellationToken ct = default);
    Task<ScoreVerificationDetailDto> GetScoreVerificationDetailAsync(string recordId, ScorePeriodFilter filter, CancellationToken ct = default);
    Task<ScoreVerificationComputedResultDto> RecalculateScoreRecordAsync(ScoreVerificationRequest request, CancellationToken ct = default);
    Task<ScoreVerificationSaveResultDto> VerifyScoreRecordAsync(ScoreVerificationRequest request, CancellationToken ct = default);
    Task<ScoreMonthClosePreviewResultDto> PreviewScoreMonthCloseAsync(ScorePeriodFilter filter, CancellationToken ct = default);
    Task<ScoreMonthCloseResultDto> CloseScoreMonthAsync(ScoreMonthCloseRequest request, CancellationToken ct = default);
    Task<ScoreMonthUndoResultDto> UndoScoreMonthCloseAsync(ScorePeriodFilter filter, CancellationToken ct = default);
    Task<ScoreOfferDownloadResult?> DownloadScoreOfferAsync(string recordId, CancellationToken ct = default);
    Task<NominaPreviewResultDto> PreviewNominaAsync(NominaPreviewRequest request, CancellationToken ct = default);
    Task<NominaConfirmResultDto> ConfirmNominaAsync(NominaConfirmRequest request, CancellationToken ct = default);
    Task<RhTableDataResultDto> GetRhTableDataAsync(string tableKey, CancellationToken ct = default);
    Task<RhSaveResultDto> SaveRhRecordAsync(RhSaveRequest request, CancellationToken ct = default);
    Task<RhFileUploadResultDto> UploadRhFieldFileAsync(string tableKey, string recordId, string fieldName, string fileName, string contentType, byte[] content, CancellationToken ct = default);
    Task<RhFileDownloadResult?> DownloadRhFieldFileAsync(string tableKey, string recordId, string fieldName, CancellationToken ct = default);
    Task<VacationRequestContextDto> GetVacationRequestContextAsync(CancellationToken ct = default);
    Task<VacationRequestSubmitResultDto> SubmitVacationRequestAsync(VacationRequestSubmitInput input, CancellationToken ct = default);
    Task<string> GetVacationRequestDocumentHtmlAsync(string recordId, bool autoPrint = false, CancellationToken ct = default);
    Task<MetricsDashboardDto> GetMetricsDashboardAsync(MetricsRangeFilter filter, MetricsViewMode view, string? sellerKey = null, CancellationToken ct = default);
    Task<BillingDashboardDto> GetBillingDashboardAsync(int year, BillingPeriodKind periodKind, int? periodValue = null, CancellationToken ct = default);
    Task<TaxesDashboardDto> GetTaxesDashboardAsync(int year, BillingPeriodKind periodKind, int? periodValue = null, CancellationToken ct = default);
    Task<PnlDashboardDto> GetPnlDashboardAsync(int year, int? monthCutoff = null, string? vertical = null, CancellationToken ct = default);
    Task<PnlCellDetailDto> GetPnlCellDetailAsync(int year, int? monthCutoff, string? vertical, string rowKey, int? cellMonth = null, CancellationToken ct = default);
    Task<PnlDetailRecordUpdateResultDto> UpdatePnlDetailRecordAsync(PnlDetailRecordUpdateRequestDto request, CancellationToken ct = default);
    Task<PortfolioDashboardDto> GetPortfolioDashboardAsync(CancellationToken ct = default);
    Task<CopiersDashboardDto> GetCopiersDashboardAsync(CancellationToken ct = default);
    Task<CopiersClientInvoicesDetailDto> GetCopiersClientInvoicesAsync(string clientId, string? clientName = null, CancellationToken ct = default);
    Task<BillingClientReportDto> GetBillingClientReportAsync(string clientId, string? clientName = null, CancellationToken ct = default);
    Task<CopiersRecordSaveResultDto> SaveCopiersRecordAsync(CopiersRecordSaveRequestDto request, CancellationToken ct = default);
    Task<CopiersEquipmentDashboardDto> GetCopiersEquipmentDashboardAsync(CancellationToken ct = default);
    Task<CopiersEquipmentDetailDto> GetCopiersEquipmentDetailAsync(string equipmentId, CancellationToken ct = default);
    Task<CopiersEquipmentInventoryDto> GetCopiersEquipmentInventoryAsync(string? clientId, string? clientName, CancellationToken ct = default);
    Task<CopiersEquipmentAssignmentResultDto> SaveCopiersEquipmentAssignmentAsync(CopiersEquipmentAssignmentRequestDto request, CancellationToken ct = default);
    Task<CopiersEquipmentSaveResultDto> SaveCopiersEquipmentAsync(CopiersEquipmentSaveRequestDto request, CancellationToken ct = default);
    Task<CopiersEquipmentMovementSaveResultDto> RegisterCopiersEquipmentMovementAsync(CopiersEquipmentMovementSaveRequestDto request, CancellationToken ct = default);
    Task<CopiersEquipmentClientSaveResultDto> SaveCopiersEquipmentClientAsync(CopiersEquipmentClientSaveRequestDto request, CancellationToken ct = default);
    Task<RhFileDownloadResult?> DownloadCopiersMaintenanceAttachmentAsync(string maintenanceId, CancellationToken ct = default);
    Task<CotizadorInterno.Web.Models.Copiers.CopiersMaintenanceBoardDto> GetCopiersMaintenanceBoardAsync(CancellationToken ct = default);
    Task<CotizadorInterno.Web.Models.Copiers.CopiersMaintenanceSaveResultDto> SaveCopiersMaintenanceAsync(CotizadorInterno.Web.Models.Copiers.CopiersMaintenanceSaveRequestDto request, CancellationToken ct = default);
    Task<CotizadorInterno.Web.Models.Copiers.CopiersMaintenanceSaveResultDto> UploadCopiersMaintenanceAttachmentAsync(string maintenanceId, string fileName, string contentType, byte[] content, CancellationToken ct = default);
    Task<CopiersSupplyInventoryDto> GetCopiersSupplyInventoryAsync(CancellationToken ct = default);
    Task<CopiersSupplyQuantityUpdateResultDto> UpdateCopiersSupplyQuantityAsync(CopiersSupplyQuantityUpdateRequestDto request, CancellationToken ct = default);
    Task<IReadOnlyList<CopiersLookupItemDto>> GetCopiersSupplyLookupAsync(string? query = null, int top = 100, CancellationToken ct = default);
    Task<CopiersSupplierInvoiceBoardDto> GetCopiersPendingSupplierInvoicesAsync(CancellationToken ct = default);
    Task<CopiersApproveSupplierInvoiceResultDto> ApproveCopiersSupplierInvoiceAsync(string invoiceId, CancellationToken ct = default);
    Task<CopiersDeliveryBoardDto> GetCopiersDeliveriesAsync(CancellationToken ct = default);
    Task<CopiersDeliverySaveResultDto> SaveCopiersDeliveryAsync(CopiersDeliverySaveRequestDto request, CancellationToken ct = default);
    Task<CopiersDeliverySaveResultDto> UploadCopiersDeliveryAttachmentAsync(string deliveryId, string fileName, string contentType, byte[] content, CancellationToken ct = default);
    Task<RhFileDownloadResult?> DownloadCopiersDeliveryAttachmentAsync(string deliveryId, CancellationToken ct = default);
    Task<CopiersSupplierInvoiceBoardDto> GetCopiersSupplierInvoicesAsync(CancellationToken ct = default);
    Task<CopiersSupplierInvoiceBatchCreateResultDto> CreateCopiersSupplierInvoicesAsync(CopiersSupplierInvoiceBatchCreateRequestDto request, CancellationToken ct = default);
    Task<IReadOnlyList<SupplierProviderLookupItem>> GetSupplierCertificateProvidersAsync(DateOnly startDate, DateOnly endDate, string? searchTerm = null, CancellationToken ct = default);
    Task<SupplierCertificateSummaryDto> GetSupplierCertificateSummaryAsync(SupplierCertificateQuery query, CancellationToken ct = default);
    Task<IReadOnlyList<ScenarioStoredDto>> GetScenariosForUserAsync(CancellationToken ct = default);
    Task UpsertScenarioAsync(ScenarioSaveRequest request, CancellationToken ct = default);
    Task DeleteScenarioAsync(string scenarioId, CancellationToken ct = default);
    Task<IReadOnlyList<EmployeeModulePermissionRowDto>> GetEmployeeModulePermissionsAsync(CancellationToken ct = default);
    Task<EmployeeModulePermissionSaveResult> SaveEmployeeModulePermissionsAsync(EmployeeModulePermissionSaveRequest request, CancellationToken ct = default);
    Task<CuentaCobroBoardDto> GetCuentasCobroBoardAsync(int year, int month, CancellationToken ct = default);
    Task<CuentaCobroSaveResultDto> SaveCuentaCobroAsync(CuentaCobroSaveRequest request, CancellationToken ct = default);
    Task<CuentaCobroFileUploadResultDto> UploadCuentaCobroAttachmentAsync(string recordId, string fileName, string contentType, byte[] content, CancellationToken ct = default);
    Task<CuentaCobroFileDownloadResult?> DownloadCuentaCobroAttachmentAsync(string recordId, CancellationToken ct = default);
    Task<CuentaCobroPrintResultDto> MarkCuentaCobroAsPrintedAsync(string recordId, CancellationToken ct = default);
    Task<CuentaCobroRowDto> GetCuentaCobroByIdAsync(string recordId, CancellationToken ct = default);
    Task<LicenciamientoBoardDto> GetLicenciamientoBoardAsync(CancellationToken ct = default);
    Task<LicenciamientoPreviewResultDto> PreviewLicenciamientoUploadAsync(string fileName, byte[] content, CancellationToken ct = default);
    Task<IReadOnlyList<LicenciamientoLookupItemDto>> SearchLicenciamientoAccountsAsync(string query, int top = 12, CancellationToken ct = default);
    Task<IReadOnlyList<LicenciamientoLookupItemDto>> SearchLicenciamientoProductsAsync(string query, int top = 12, CancellationToken ct = default);
    Task<LicenciamientoRegisterAccountIdResultDto> RegisterLicenciamientoAccountIdAsync(LicenciamientoRegisterAccountIdRequestDto request, CancellationToken ct = default);
    Task<LicenciamientoRegisterProductResultDto> RegisterLicenciamientoProductAsync(LicenciamientoRegisterProductRequestDto request, CancellationToken ct = default);
    Task<LicenciamientoImportResultDto> ImportLicenciamientoRowsAsync(LicenciamientoImportRequestDto request, CancellationToken ct = default);
    Task<LicenciamientoAdjustTrmResultDto> AdjustLicenciamientoTrmAsync(LicenciamientoAdjustTrmRequestDto request, CancellationToken ct = default);
    Task<LicenciamientoUpdateContractTypeResultDto> UpdateLicenciamientoContractTypeAsync(LicenciamientoUpdateContractTypeRequestDto request, CancellationToken ct = default);
    Task<HardwareCsvPreviewResultDto> PreviewHardwareCsvAsync(string fileName, byte[] content, CancellationToken ct = default);
    Task<HardwareProvisionResultDto> ProvisionHardwareCsvAsync(string fileName, byte[] content, CancellationToken ct = default);
    Task<HardwareBoardDto> GetHardwareBoardAsync(int? stateValue = null, DateOnly? startDate = null, DateOnly? endDate = null, CancellationToken ct = default, bool currentOwnerOnly = false);
    Task<HardwareOrderCreateResultDto> CreateHardwareOrderDraftAsync(HardwareOrderCreateRequest request, CancellationToken ct = default);
    Task<HardwareBulkEditResultDto> UpdateHardwareCommercialDraftAsync(HardwareOrderLineEditRequest request, CancellationToken ct = default);
    Task<HardwareSaveResultDto> SaveHardwareStageAsync(HardwareStageSaveRequest request, CancellationToken ct = default, bool requireCurrentOwner = false);
    Task<HardwareBulkEditResultDto> SaveHardwareRecordsAsync(HardwareBulkEditRequest request, CancellationToken ct = default);
    Task<HardwareFileUploadResultDto> UploadHardwareFileAsync(string recordId, string fieldName, string fileName, string contentType, byte[] content, CancellationToken ct = default, bool requireCurrentOwner = false);
    Task<HardwareFileDownloadResult?> DownloadHardwareFileAsync(string recordId, string fieldName, CancellationToken ct = default, bool requireCurrentOwner = false);
    Task<IReadOnlyList<HardwareInvoiceLookupItemDto>> SearchHardwareInvoicesAsync(string query, int top = 12, CancellationToken ct = default);
    Task<SoporteCloudBoardDto> GetSoporteCloudBoardAsync(DateOnly? startDate = null, DateOnly? endDate = null, CancellationToken ct = default);
    Task<SoporteCloudSaveResultDto> SaveSoporteCloudTicketAsync(SoporteCloudSaveRequest request, CancellationToken ct = default);
    Task<SoporteCloudFileUploadResultDto> UploadSoporteCloudAttachmentAsync(string recordId, string fileName, string contentType, byte[] content, CancellationToken ct = default);
    Task<SoporteCloudFileDownloadResult?> DownloadSoporteCloudAttachmentAsync(string recordId, CancellationToken ct = default);
}
